import { genNodeId } from "../../../../../schema/node";
import { UPDATE_MODE } from "../../../../settings";
import { mainGraph } from "../../../../store";
import { CircuitPosition, NodeEdge } from "../../../edges/nodeEdge";

const SIN_ID = "sin00000";
const DIVIDER_ID = "divider0";

export const SIN_CONFIG_JSON = {
  primitive: false as const,
  subgraph: {
    edges: [
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "4h7CMXcp", handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "4h7CMXcp", handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "4h7CMXcp",
        selected: false,
        operator: {
          primitive: false,
          bound: 1,
          interfaceVertexIds: [
            { node: "inputmu", handle: 0 },
            { node: "outputmu", handle: 0 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "EPDDzMKY", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: -1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "EPDDzMKY", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "EPDDzMKY", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "EPDDzMKY",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: true,
                position: { x: 331.6279478186962, y: 414.3879980708546 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "8RbDj3zb",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 1.9690865162394289, y: 398.891213992534 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "WTD9LYzp",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 444.7588959666771, y: 759.7700391093557 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 1, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "inputmu",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: true,
                position: { x: 138.62254611597575, y: 41.05638163858521 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "yJMXBRCT",
                selected: false,
                operator: { primitive: true, type: "adder", bound: 2 },
                hidden: true,
                position: { x: 111.52032792318755, y: 1089.7749480771463 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "outputmu",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 0 },
                hidden: true,
                position: { x: -326.03048175429785, y: 838.6867117464919 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "EPDDzMKY", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "nctJcKNE",
                selected: false,
                source: { node: "EPDDzMKY", handle: 2 },
                target: { node: "WTD9LYzp", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "U7qLi6Mj",
                selected: false,
                source: { node: "inputmu", handle: 2 },
                target: { node: "8RbDj3zb", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "EPDDzMKY", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "8iGG3q9t",
                selected: false,
                source: { node: "inputmu", handle: 2 },
                target: { node: "EPDDzMKY", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "K7qdU7LR",
                selected: false,
                source: { node: "8RbDj3zb", handle: 1 },
                target: { node: "yJMXBRCT", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "Aw9TQ6Fr",
                selected: false,
                source: { node: "WTD9LYzp", handle: 1 },
                target: { node: "yJMXBRCT", handle: 1 },
              },
              {
                vertices: [
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "ee8HieMD",
                selected: false,
                source: { node: "yJMXBRCT", handle: 2 },
                target: { node: "outputmu", handle: 2 },
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 362.65277099609375, y: 559.1163177490234 },
        label: "cos",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SIN_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SIN_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: SIN_ID,
        selected: false,
        operator: {
          primitive: false,
          bound: 1,
          interfaceVertexIds: [
            { node: "inputmu", handle: 0 },
            { node: "outputmu", handle: 0 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "internal", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: -1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "internal", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "internal", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "internal",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: true,
                position: { x: 331.6279478186962, y: 414.3879980708546 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "8RbDj3zb",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 1.9690865162394289, y: 398.891213992534 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "WTD9LYzp",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 444.7588959666771, y: 759.7700391093557 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 1, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "inputmu",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: true,
                position: { x: 138.62254611597575, y: 41.05638163858521 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "yJMXBRCT",
                selected: false,
                operator: { primitive: true, type: "adder", bound: 0 },
                hidden: true,
                position: { x: 379.96951824570215, y: 1126.686711746492 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 2, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "outputmu",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 0 },
                hidden: true,
                position: { x: -326.03048175429785, y: 838.6867117464919 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "internal", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "nctJcKNE",
                selected: false,
                source: { node: "internal", handle: 2 },
                target: { node: "WTD9LYzp", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "U7qLi6Mj",
                selected: false,
                source: { node: "inputmu", handle: 2 },
                target: { node: "8RbDj3zb", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "inputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "internal", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "8iGG3q9t",
                selected: false,
                source: { node: "inputmu", handle: 2 },
                target: { node: "internal", handle: 0 },
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "8RbDj3zb", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "FLh6mKni",
                selected: false,
                source: { node: "8RbDj3zb", handle: 1 },
                target: { node: "yJMXBRCT", handle: 2 },
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "WTD9LYzp", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "AGqdp4yh",
                selected: false,
                source: { node: "WTD9LYzp", handle: 1 },
                target: { node: "yJMXBRCT", handle: 1 },
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "yJMXBRCT", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "outputmu", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "8UXCDzWB",
                selected: false,
                source: { node: "yJMXBRCT", handle: 0 },
                target: { node: "outputmu", handle: 2 },
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 102.65277099609375, y: 568.1163177490234 },
        label: "sin",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 2 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: DIVIDER_ID,
        selected: false,
        operator: {
          primitive: false,
          bound: 2,
          interfaceVertexIds: [
            { node: "multiply", handle: 2 },
            { node: "multiply", handle: 1 },
            { node: "multiply", handle: 0 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "multiply",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 0 },
                hidden: true,
                position: { x: 0, y: 0 },
                label: "",
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 167.6591338810059, y: 859.6156814605322 },
        label: "÷",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SIN_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "Kt3KXnmf",
        selected: false,
        source: { node: SIN_ID, handle: 1 },
        target: { node: DIVIDER_ID, handle: 0 },
      },
      {
        vertices: [
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "4h7CMXcp", handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "gk7w6P6c",
        selected: false,
        source: { node: "4h7CMXcp", handle: 1 },
        target: { node: DIVIDER_ID, handle: 1 },
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SIN_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "4h7CMXcp", handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "zCKBnXNE",
        selected: false,
        source: { node: SIN_ID, handle: 0 },
        target: { node: "4h7CMXcp", handle: 0 },
      },
    ],
    mode: 1,
    focus: null,
  },
  bound: 1,
  interfaceVertexIds: [
    {
      node: SIN_ID,
      handle: 0,
    },
    {
      node: DIVIDER_ID,
      handle: 2,
    },
  ],
};

export const addTan = (position: CircuitPosition) => {
  const id = genNodeId();
  const vertices = [
    mainGraph.addFree(0, 0, { node: id, handle: 0 }),
    mainGraph.addFree(0, 0, { node: id, handle: 1 }),
  ];
  const edge = new NodeEdge(
    vertices,
    SIN_CONFIG_JSON,
    UPDATE_MODE,
    id,
    position,
    false,
    false,
    "tan(a)"
  );
  mainGraph.edges.push(edge);
};
