import { genNodeId } from "../../../../../schema/node";
import { UPDATE_MODE } from "../../../../settings";
import { mainGraph } from "../../../../store";
import { CircuitPosition, NodeEdge } from "../../../edges/nodeEdge";

const SINH_ID = "sinhsinh";
const DIVIDER_ID = "divide00";

export const TANH_CONFIG_JSON = {
  primitive: false as const,
  subgraph: {
    edges: [
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SINH_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SINH_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: SINH_ID,
        selected: false,
        operator: {
          primitive: false,
          bound: 1,
          interfaceVertexIds: [
            { node: "multiply", handle: 0 },
            { node: "divide00", handle: 2 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: -1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "multiply",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: true,
                position: { x: 404.0309261200257, y: 506.2621085337307 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "DiAhJyTA",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 304.6728108509008, y: 771.9115239819547 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "rHabMQPh",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: true,
                position: { x: 636.0594311727974, y: 803.9811969163318 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "fDJK7mhr",
                selected: false,
                operator: {
                  primitive: false,
                  bound: 2,
                  interfaceVertexIds: [
                    { node: "adder000", handle: 2 },
                    { node: "adder000", handle: 1 },
                    { node: "adder000", handle: 0 },
                  ],
                  subgraph: {
                    edges: [
                      {
                        vertices: [
                          {
                            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "adder000", handle: 0 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "adder000", handle: 1 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "adder000", handle: 2 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                        ],
                        id: "adder000",
                        selected: false,
                        operator: { primitive: true, type: "adder", bound: 0 },
                        hidden: true,
                        position: { x: 0, y: 0 },
                        label: "",
                      },
                    ],
                    mode: 1,
                    focus: null,
                  },
                },
                hidden: true,
                position: { x: 387.1376841107276, y: 1121.6236716949238 },
                label: "a - b",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "divide00",
                selected: false,
                operator: {
                  primitive: false,
                  bound: 2,
                  interfaceVertexIds: [
                    { node: "multiply", handle: 2 },
                    { node: "multiply", handle: 1 },
                    { node: "multiply", handle: 0 },
                  ],
                  subgraph: {
                    edges: [
                      {
                        vertices: [
                          {
                            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 0 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 1 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 2 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                        ],
                        id: "multiply",
                        selected: false,
                        operator: { primitive: true, type: "multiplier", bound: 0 },
                        hidden: true,
                        position: { x: 0, y: 0 },
                        label: "",
                      },
                    ],
                    mode: 1,
                    focus: null,
                  },
                },
                hidden: true,
                position: { x: 651.9440836767947, y: 1455.011453108759 },
                label: "a ÷ b",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "mmXTNtdY",
                selected: false,
                source: { node: "multiply", handle: 0 },
                target: { node: "DiAhJyTA", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "GWmqEJUK",
                selected: false,
                source: { node: "multiply", handle: 2 },
                target: { node: "rHabMQPh", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "KwJjBGa6",
                selected: false,
                source: { node: "DiAhJyTA", handle: 1 },
                target: { node: "fDJK7mhr", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "m8HECEmj",
                selected: false,
                source: { node: "rHabMQPh", handle: 1 },
                target: { node: "fDJK7mhr", handle: 1 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "fDJK7mhr", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "nLkytKwe",
                selected: false,
                source: { node: "fDJK7mhr", handle: 2 },
                target: { node: "divide00", handle: 0 },
                primaryLeft: true,
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 153.8014780291781, y: 831.1750200480624 },
        label: "sinh(a)",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "xKLTpktn", handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "xKLTpktn", handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "xKLTpktn",
        selected: false,
        operator: {
          primitive: false,
          bound: 1,
          interfaceVertexIds: [
            { node: "multiply", handle: 0 },
            { node: "divide00", handle: 2 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: -1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "multiply",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 2 },
                hidden: false,
                position: { x: 404.0309261200257, y: 506.2621085337307 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "DiAhJyTA",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: false,
                position: { x: 304.6728108509008, y: 771.9115239819547 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "rHabMQPh",
                selected: false,
                operator: { primitive: true, type: "exponential", bound: 1 },
                hidden: false,
                position: { x: 636.0594311727974, y: 803.9811969163318 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 2 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "4XBtEwAA",
                selected: false,
                operator: { primitive: true, type: "adder", bound: 2 },
                hidden: false,
                position: { x: 392.5751195453314, y: 1195.188416034307 },
                label: "",
              },
              {
                vertices: [
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 2 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "divide00",
                selected: false,
                operator: {
                  primitive: false,
                  bound: 2,
                  interfaceVertexIds: [
                    { node: "multiply", handle: 2 },
                    { node: "multiply", handle: 1 },
                    { node: "multiply", handle: 0 },
                  ],
                  subgraph: {
                    edges: [
                      {
                        vertices: [
                          {
                            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 0 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 1 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                          {
                            value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                            id: { node: "multiply", handle: 2 },
                            dragging: false,
                            hidden: true,
                            selected: false,
                          },
                        ],
                        id: "multiply",
                        selected: false,
                        operator: { primitive: true, type: "multiplier", bound: 0 },
                        hidden: true,
                        position: { x: 0, y: 0 },
                        label: "",
                      },
                    ],
                    mode: 1,
                    focus: null,
                  },
                },
                hidden: false,
                position: { x: 844.5751195453314, y: 1571.188416034307 },
                label: "a ÷ b",
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "mmXTNtdY",
                selected: false,
                source: { node: "multiply", handle: 0 },
                target: { node: "DiAhJyTA", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "GWmqEJUK",
                selected: false,
                source: { node: "multiply", handle: 2 },
                target: { node: "rHabMQPh", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "DiAhJyTA", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "warXcf4N",
                selected: false,
                source: { node: "DiAhJyTA", handle: 1 },
                target: { node: "4XBtEwAA", handle: 0 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "rHabMQPh", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 1 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "bzjYyr6B",
                selected: false,
                source: { node: "rHabMQPh", handle: 1 },
                target: { node: "4XBtEwAA", handle: 1 },
                primaryLeft: true,
              },
              {
                vertices: [
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "4XBtEwAA", handle: 2 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                  {
                    value: { x: 2, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "divide00", handle: 0 },
                    dragging: false,
                    hidden: false,
                    selected: false,
                  },
                ],
                id: "xeCjjkYi",
                selected: false,
                source: { node: "4XBtEwAA", handle: 2 },
                target: { node: "divide00", handle: 0 },
                primaryLeft: true,
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 327.27087417941175, y: 829.4336015224906 },
        label: "cosh(a)",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 2 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: DIVIDER_ID,
        selected: false,
        operator: {
          primitive: false,
          bound: 2,
          interfaceVertexIds: [
            { node: "multiply", handle: 2 },
            { node: "multiply", handle: 1 },
            { node: "multiply", handle: 0 },
          ],
          subgraph: {
            edges: [
              {
                vertices: [
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 0 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 1 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                  {
                    value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
                    id: { node: "multiply", handle: 2 },
                    dragging: false,
                    hidden: true,
                    selected: false,
                  },
                ],
                id: "multiply",
                selected: false,
                operator: { primitive: true, type: "multiplier", bound: 0 },
                hidden: true,
                position: { x: 0, y: 0 },
                label: "",
              },
            ],
            mode: 1,
            focus: null,
          },
        },
        hidden: false,
        position: { x: 166.87600247285684, y: 1094.8620082677521 },
        label: "a ÷ b",
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SINH_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "xKLTpktn", handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "kEbNzpdT",
        selected: false,
        source: { node: SINH_ID, handle: 0 },
        target: { node: "xKLTpktn", handle: 0 },
        primaryLeft: true,
      },
      {
        vertices: [
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: SINH_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 0, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 0 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "Ct6irLpK",
        selected: false,
        source: { node: SINH_ID, handle: 1 },
        target: { node: DIVIDER_ID, handle: 0 },
        primaryLeft: true,
      },
      {
        vertices: [
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: "xKLTpktn", handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
          {
            value: { x: 1, y: 0, delta: { x: 0, y: 0 } },
            id: { node: DIVIDER_ID, handle: 1 },
            dragging: false,
            hidden: false,
            selected: false,
          },
        ],
        id: "pjLcfLjQ",
        selected: false,
        source: { node: "xKLTpktn", handle: 1 },
        target: { node: DIVIDER_ID, handle: 1 },
        primaryLeft: true,
      },
    ],
    mode: 1,
    focus: null,
  },
  bound: 1,
  interfaceVertexIds: [
    {
      node: SINH_ID,
      handle: 0,
    },
    {
      node: DIVIDER_ID,
      handle: 2,
    },
  ],
};

export const addTanh = (position: CircuitPosition) => {
  const id = genNodeId();
  const vertices = [
    mainGraph.addFree(0, 0, { node: id, handle: 0 }),
    mainGraph.addFree(0, 0, { node: id, handle: 1 }),
  ];
  const edge = new NodeEdge(
    vertices,
    TANH_CONFIG_JSON,
    UPDATE_MODE,
    id,
    position,
    false,
    false,
    "tanh(a)"
  );
  mainGraph.edges.push(edge);
};
